image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - pip install sphinx_rtd_theme-0.2.5b2-py2.py3-none-any.whl
  - apk --no-cache add make
  - make html
  - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
