language: python

install:
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme

script: make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
