language: python
python:
  - "2.7"

install:
  - pip install --user python-sphinx

deploy:
  provider: pages
  skip-cleanup: true
  github-token: gh-token
  keep-history: true
  on:
    branch: master