language: python

install:
  - pip install -U sphinx

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 5b56891ec8fa609b220912117e50160d718a11ec
  keep-history: true
  on:
    branch: master
